### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Aagney-github**

### CODE REVIEW

**Comment by asiawin** [comment]
Thanks for contributing to my project!

**Comment by Aagney-github** [comment]
> Thanks for contributing to my project!

you are welcome

**Comment by asiawin** [comment]
If you want more fun developing with me, you can do more editing.

**Comment by Aagney-github** [comment]
> If you want more fun developing with me, you can do more editing.

ok i am definetly having fun

**Comment by asiawin** [comment]
Be sure to follow CadexOS targets when modifying code.!

  
CadexOS is an operating system made for x86 PCs  
Features of CadexOS:

*   It is x86
*   It has its own bootloader
*   It is based on UNIX
*   It has an ELF parser
*   It supports C++ apps
*   You can make GUI apps using C++ and TrueGL C++ library.
*   And many more! (see [README.md](https://github.com/CadexOS/Cadex-OS-Official/blob/master/README.md))

**Pull request merged**
